name: Build Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install ESP32 Board
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Patch custom board definition
        run: |
          mkdir -p $HOME/.arduino15/packages/esp32/hardware/esp32/3.2.0/
          cp .boardfix/boards.local.txt $HOME/.arduino15/packages/esp32/hardware/esp32/3.2.0/

      - name: Compile Sketch with RainMaker Partition
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32doit-devkit-v1.rainmaker \
            --output-dir output \
            compiler.ino
            --verbose
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: output/compiler.ino.bin
