name: ESP32 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python (needed for arduino-cli)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install arduino-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Show ESP32 Boards and Partition Schemes
        run: |
          arduino-cli board listall esp32:esp32
          arduino-cli board details esp32:esp32:esp32doit-devkit-v1

      - name: Show available partitions
        run: |
          ls $HOME/.arduino15/packages/esp32/hardware/esp32/*/tools/partitions/
          ls $HOME/.arduino15/packages/esp32/hardware/esp32/*/tools/partitions/huge_app.csv

      - name: Compile Sketch with huge_app partition
        run: |
          arduino-cli compile \
            --fqbn esp32:esp32:esp32doit-devkit-v1 \
            --build-property build.partitions=huge_app \
            --output-dir output_huge \
            --verbose \
            compiler.ino

      - name: Upload compiled binaries
        uses: actions/upload-artifact@v4
        with:
          name: esp32-binaries
          path: output_huge/*.bin
